# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install -g https://artifactory.app.protego.io/cloudguard-serverless-plugin.tgz
  displayName: 'npm install'

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
  displayName: 'Install Docker'

- task: AWSShellScript@1
  inputs:
      awsCredentials: 'aws-rolandopcp'
      regionName: 'us-east-1'
      scriptType: 'inline'
      inlineScript: 'cloudguard proact -t $(CLOUDGUARD_TOKEN)'
  displayName: 'Running CloudGuard Proact'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/cloudguard'
    artifact: 'cloudguard_output'
    publishLocation: 'pipeline'
  displayName: 'Publishing Artifacts'